name: WhatsApp Bot

on:
  schedule:
    - cron: '47 15 * * *'  # Runs every day at 18:00 UTC (adjust as needed)
  workflow_dispatch:  # Allows you to trigger the workflow manually

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v3

      - name: 🟢 Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: 📦 Install Dependencies
        run: |
          npm install  # Installs the dependencies in the repository

      - name: 🚀 Run WhatsApp Bot
        run: |
          npm start  # Runs the bot using the start script defined in package.json
